### ISSUE TITLE
Improved code

### ISSUE THREAD

**Issue by vishalrajputt** [milkyicedtea/FileFolder#1]
You can use  `pathlib.Path` instead of os module
It provides a more object-oriented approach to dealing with file and directory paths. It makes it easier to perform path manipulation and avoids the use of string concatenation.

Replace the os functions used in the code.

```
from pathlib import Path
directory = Path(askdirectory())
if not directory.is_dir():  
    print("Can't continue without a valid directory! Closing here..")
    exit()
os.chdir(directory)
```

**Comment by milkyicedtea** [comment]
Marking this as closed after [this commit](https://github.com/milkyicedtea/FileFolder/commit/14438f05a0409b6194f7ee18bdf3111af262ef08), feel free to reopen for anything!
